"""add foreign key to Review

Revision ID: 702592c315d1
Revises: 9e17fbbb20c3
Create Date: 2025-01-19 17:38:44.240635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702592c315d1'
down_revision = '9e17fbbb20c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
